import { supabase } from '@/integrations/supabase/client';
import { FormTemplate, FormField } from '@/types/form-builder';

export async function seedFormTemplates(companyId: string) {
  const templates: Omit<FormTemplate, 'id' | 'created_at' | 'updated_at' | 'created_by' | 'updated_by'>[] = [
    // Hardware Request
    {
      company_id: companyId,
      name: 'Hardware Request',
      description: 'Standard hardware request form for IT equipment and devices',
      form_type: 'hardware',
      fields: [
        {
          id: 'item_name',
          type: 'text',
          label: 'Item Name',
          placeholder: 'Enter item name',
          required: true,
          order: 0,
          validation: { max: 200 },
        },
        {
          id: 'catalog_item',
          type: 'catalog_item',
          label: 'Or Select from Catalog',
          description: 'Quick select from hardware catalog',
          required: false,
          order: 1,
        },
        {
          id: 'priority',
          type: 'select',
          label: 'Priority',
          required: true,
          order: 2,
          options: [
            { label: 'Low', value: 'low' },
            { label: 'Medium', value: 'medium' },
            { label: 'High', value: 'high' },
            { label: 'Urgent', value: 'urgent' },
          ],
          defaultValue: 'medium',
        },
        {
          id: 'quantity',
          type: 'number',
          label: 'Quantity',
          required: true,
          order: 3,
          defaultValue: 1,
          validation: { min: 1 },
        },
        {
          id: 'clinic_name',
          type: 'text',
          label: 'Clinic/Department Name',
          placeholder: 'Enter clinic or department name',
          required: false,
          order: 4,
        },
        {
          id: 'location',
          type: 'location',
          label: 'Location',
          description: 'Select delivery location',
          required: false,
          order: 5,
        },
        {
          id: 'model_number',
          type: 'text',
          label: 'Model Number',
          placeholder: 'Enter model number if known',
          required: false,
          order: 6,
        },
        {
          id: 'business_justification',
          type: 'textarea',
          label: 'Business Justification',
          placeholder: 'Explain why this item is needed',
          required: false,
          order: 7,
        },
      ],
      is_active: true,
      settings: {},
    },

    // Marketing Request
    {
      company_id: companyId,
      name: 'Marketing Request',
      description: 'Request for fax blasts, email blasts, and website updates',
      form_type: 'marketing',
      fields: [
        {
          id: 'title',
          type: 'text',
          label: 'Request Title',
          placeholder: 'Enter request title',
          required: true,
          order: 0,
          validation: { max: 200 },
        },
        {
          id: 'request_type',
          type: 'select',
          label: 'Request Type',
          required: true,
          order: 1,
          options: [
            { label: 'Fax Blast', value: 'fax_blast' },
            { label: 'Email Blast', value: 'email_blast' },
            { label: 'Website Update', value: 'website_update' },
          ],
          defaultValue: 'email_blast',
        },
        {
          id: 'priority',
          type: 'select',
          label: 'Priority',
          required: true,
          order: 2,
          options: [
            { label: 'Low', value: 'low' },
            { label: 'Medium', value: 'medium' },
            { label: 'High', value: 'high' },
            { label: 'Urgent', value: 'urgent' },
          ],
          defaultValue: 'medium',
        },
        {
          id: 'brand',
          type: 'text',
          label: 'Brand',
          placeholder: 'Enter brand name',
          required: false,
          order: 3,
        },
        {
          id: 'clinic',
          type: 'text',
          label: 'Clinic',
          placeholder: 'Enter clinic name',
          required: false,
          order: 4,
        },
        {
          id: 'description',
          type: 'textarea',
          label: 'Description',
          placeholder: 'Provide details about your request',
          required: false,
          order: 5,
        },
        {
          id: 'website_update_details',
          type: 'textarea',
          label: 'Website Update Details',
          placeholder: 'Describe the website changes needed',
          description: 'Only for website update requests',
          required: false,
          order: 6,
        },
        {
          id: 'scheduled_send_date',
          type: 'date',
          label: 'Scheduled Send Date',
          description: 'Optional: Schedule for future delivery',
          required: false,
          order: 7,
        },
        {
          id: 'is_recurring',
          type: 'checkbox',
          label: 'Set as Recurring',
          description: 'Make this a recurring campaign',
          required: false,
          order: 8,
        },
      ],
      is_active: true,
      settings: {},
    },

    // Toner Request
    {
      company_id: companyId,
      name: 'Toner Request',
      description: 'Order toner cartridges for printers',
      form_type: 'toner',
      fields: [
        {
          id: 'title',
          type: 'text',
          label: 'Request Title',
          placeholder: 'e.g., Toner for Reception Printer',
          required: true,
          order: 0,
          validation: { max: 200 },
        },
        {
          id: 'site',
          type: 'location',
          label: 'Site/Location',
          required: true,
          order: 1,
        },
        {
          id: 'printer_model',
          type: 'text',
          label: 'Printer Model',
          placeholder: 'e.g., HP LaserJet Pro M404dn',
          required: true,
          order: 2,
        },
        {
          id: 'colors_required',
          type: 'multiselect',
          label: 'Colors Required',
          required: true,
          order: 3,
          options: [
            { label: 'Black', value: 'black' },
            { label: 'Cyan', value: 'cyan' },
            { label: 'Magenta', value: 'magenta' },
            { label: 'Yellow', value: 'yellow' },
          ],
        },
        {
          id: 'quantity',
          type: 'number',
          label: 'Quantity',
          required: true,
          order: 4,
          defaultValue: 1,
          validation: { min: 1 },
        },
        {
          id: 'urgency',
          type: 'select',
          label: 'Urgency',
          required: true,
          order: 5,
          options: [
            { label: 'Normal', value: 'normal' },
            { label: 'Urgent', value: 'urgent' },
            { label: 'Critical', value: 'critical' },
          ],
          defaultValue: 'normal',
        },
        {
          id: 'description',
          type: 'textarea',
          label: 'Additional Notes',
          placeholder: 'Any additional information',
          required: false,
          order: 6,
        },
      ],
      is_active: true,
      settings: {},
    },

    // User Account Request
    {
      company_id: companyId,
      name: 'User Account Request',
      description: 'Request new Active Directory user account',
      form_type: 'user_account',
      fields: [
        {
          id: 'first_name',
          type: 'text',
          label: 'First Name',
          placeholder: 'Enter first name',
          required: true,
          order: 0,
        },
        {
          id: 'last_name',
          type: 'text',
          label: 'Last Name',
          placeholder: 'Enter last name',
          required: true,
          order: 1,
        },
        {
          id: 'email',
          type: 'email',
          label: 'Email Address',
          placeholder: 'user@company.com',
          required: true,
          order: 2,
        },
        {
          id: 'department',
          type: 'text',
          label: 'Department',
          placeholder: 'Enter department',
          required: true,
          order: 3,
        },
        {
          id: 'job_title',
          type: 'text',
          label: 'Job Title',
          placeholder: 'Enter job title',
          required: true,
          order: 4,
        },
        {
          id: 'manager_name',
          type: 'text',
          label: 'Manager Name',
          placeholder: 'Enter manager name',
          required: true,
          order: 5,
        },
        {
          id: 'start_date',
          type: 'date',
          label: 'Start Date',
          required: true,
          order: 6,
        },
        {
          id: 'office365_license',
          type: 'select',
          label: 'Office 365 License',
          required: true,
          order: 7,
          options: [
            { label: 'Microsoft 365 Business Basic', value: 'microsoft_365_business_basic' },
            { label: 'Microsoft 365 Business Standard', value: 'microsoft_365_business_standard' },
            { label: 'Microsoft 365 Business Premium', value: 'microsoft_365_business_premium' },
            { label: 'Microsoft 365 E3', value: 'microsoft_365_e3' },
            { label: 'Microsoft 365 E5', value: 'microsoft_365_e5' },
            { label: 'Office 365 E1', value: 'office_365_e1' },
            { label: 'Office 365 E3', value: 'office_365_e3' },
            { label: 'Office 365 E5', value: 'office_365_e5' },
          ],
        },
      ],
      is_active: true,
      settings: {},
    },

    // HR Department Request
    {
      company_id: companyId,
      name: 'HR Request',
      description: 'Human Resources request form',
      form_type: 'department',
      department: 'hr',
      fields: [
        {
          id: 'title',
          type: 'text',
          label: 'Request Title',
          placeholder: 'Enter request title',
          required: true,
          order: 0,
          validation: { max: 200 },
        },
        {
          id: 'sub_department',
          type: 'select',
          label: 'Request Type',
          required: true,
          order: 1,
          options: [
            { label: 'Incident form submission', value: 'Incident form submission' },
            { label: 'Patient complaint', value: 'Patient complaint' },
            { label: 'Staff complaint', value: 'Staff complaint' },
            { label: 'Report HR compliance', value: 'Report HR compliance' },
            { label: 'General support', value: 'General support' },
          ],
        },
        {
          id: 'priority',
          type: 'select',
          label: 'Priority',
          required: true,
          order: 2,
          options: [
            { label: 'Low', value: 'low' },
            { label: 'Medium', value: 'medium' },
            { label: 'High', value: 'high' },
            { label: 'Urgent', value: 'urgent' },
          ],
          defaultValue: 'medium',
        },
        {
          id: 'location_id',
          type: 'location',
          label: 'Location',
          required: false,
          order: 3,
        },
        {
          id: 'description',
          type: 'textarea',
          label: 'Description',
          placeholder: 'Provide detailed information about your request',
          required: true,
          order: 4,
        },
      ],
      is_active: true,
      settings: {},
    },

    // Accounts Payable Request
    {
      company_id: companyId,
      name: 'Accounts Payable Request',
      description: 'Submit EFT payments and reimbursement requests',
      form_type: 'department',
      department: 'accounts_payable',
      fields: [
        {
          id: 'title',
          type: 'text',
          label: 'Request Title',
          placeholder: 'Enter request title',
          required: true,
          order: 0,
          validation: { max: 200 },
        },
        {
          id: 'sub_department',
          type: 'select',
          label: 'Request Type',
          required: true,
          order: 1,
          options: [
            { label: 'EFT payment', value: 'EFT payment' },
            { label: 'Staff Reimbursement request', value: 'Staff Reimbursement request' },
            { label: 'General Inquiry', value: 'General Inquiry' },
          ],
        },
        {
          id: 'priority',
          type: 'select',
          label: 'Priority',
          required: true,
          order: 2,
          options: [
            { label: 'Low', value: 'low' },
            { label: 'Medium', value: 'medium' },
            { label: 'High', value: 'high' },
            { label: 'Urgent', value: 'urgent' },
          ],
          defaultValue: 'medium',
        },
        {
          id: 'location_id',
          type: 'location',
          label: 'Location',
          required: false,
          order: 3,
        },
        {
          id: 'description',
          type: 'textarea',
          label: 'Description',
          placeholder: 'Provide detailed information about your request',
          required: true,
          order: 4,
        },
      ],
      is_active: true,
      settings: {},
    },

    // Finance Request
    {
      company_id: companyId,
      name: 'Finance Request',
      description: 'Submit finance-related requests',
      form_type: 'department',
      department: 'finance',
      fields: [
        {
          id: 'title',
          type: 'text',
          label: 'Request Title',
          placeholder: 'Enter request title',
          required: true,
          order: 0,
          validation: { max: 200 },
        },
        {
          id: 'sub_department',
          type: 'select',
          label: 'Request Type',
          required: true,
          order: 1,
          options: [
            { label: 'Statement request', value: 'Statement request' },
            { label: 'Payroll issues', value: 'Payroll issues' },
          ],
        },
        {
          id: 'priority',
          type: 'select',
          label: 'Priority',
          required: true,
          order: 2,
          options: [
            { label: 'Low', value: 'low' },
            { label: 'Medium', value: 'medium' },
            { label: 'High', value: 'high' },
            { label: 'Urgent', value: 'urgent' },
          ],
          defaultValue: 'medium',
        },
        {
          id: 'location_id',
          type: 'location',
          label: 'Location',
          required: false,
          order: 3,
        },
        {
          id: 'description',
          type: 'textarea',
          label: 'Description',
          placeholder: 'Provide detailed information about your request',
          required: true,
          order: 4,
        },
      ],
      is_active: true,
      settings: {},
    },

    // Facility Services Request
    {
      company_id: companyId,
      name: 'Facility Services Request',
      description: 'Submit facility and maintenance requests',
      form_type: 'department',
      department: 'facility_services',
      fields: [
        {
          id: 'title',
          type: 'text',
          label: 'Request Title',
          placeholder: 'Enter request title',
          required: true,
          order: 0,
          validation: { max: 200 },
        },
        {
          id: 'sub_department',
          type: 'select',
          label: 'Request Type',
          required: true,
          order: 1,
          options: [
            { label: 'General maintenance', value: 'General maintenance' },
            { label: 'Airconditioning', value: 'Airconditioning' },
            { label: 'Lighting', value: 'Lighting' },
            { label: 'Cleaning', value: 'Cleaning' },
            { label: 'Merchandise', value: 'Merchandise' },
            { label: 'Other', value: 'Other' },
          ],
        },
        {
          id: 'priority',
          type: 'select',
          label: 'Priority',
          required: true,
          order: 2,
          options: [
            { label: 'Low', value: 'low' },
            { label: 'Medium', value: 'medium' },
            { label: 'High', value: 'high' },
            { label: 'Urgent', value: 'urgent' },
          ],
          defaultValue: 'medium',
        },
        {
          id: 'location_id',
          type: 'location',
          label: 'Location',
          required: false,
          order: 3,
        },
        {
          id: 'description',
          type: 'textarea',
          label: 'Description',
          placeholder: 'Provide detailed information about your request',
          required: true,
          order: 4,
        },
      ],
      is_active: true,
      settings: {},
    },

    // Office Services Request
    {
      company_id: companyId,
      name: 'Office Services Request',
      description: 'Submit office services requests',
      form_type: 'department',
      department: 'office_services',
      fields: [
        {
          id: 'title',
          type: 'text',
          label: 'Request Title',
          placeholder: 'Enter request title',
          required: true,
          order: 0,
          validation: { max: 200 },
        },
        {
          id: 'sub_department',
          type: 'select',
          label: 'Request Type',
          required: true,
          order: 1,
          options: [
            { label: 'Print and Post', value: 'Print and Post' },
            { label: 'Couriers and Deliveries', value: 'Couriers and Deliveries' },
            { label: 'Stationary Requests', value: 'Stationary Requests' },
            { label: 'Marketing and Print material request', value: 'Marketing and Print material request' },
          ],
        },
        {
          id: 'priority',
          type: 'select',
          label: 'Priority',
          required: true,
          order: 2,
          options: [
            { label: 'Low', value: 'low' },
            { label: 'Medium', value: 'medium' },
            { label: 'High', value: 'high' },
            { label: 'Urgent', value: 'urgent' },
          ],
          defaultValue: 'medium',
        },
        {
          id: 'location_id',
          type: 'location',
          label: 'Location',
          required: false,
          order: 3,
        },
        {
          id: 'description',
          type: 'textarea',
          label: 'Description',
          placeholder: 'Provide detailed information about your request',
          required: true,
          order: 4,
        },
      ],
      is_active: true,
      settings: {},
    },

    // IT Service Desk Request
    {
      company_id: companyId,
      name: 'IT Service Desk Request',
      description: 'Submit IT support and service requests',
      form_type: 'department',
      department: 'it_service_desk',
      fields: [
        {
          id: 'title',
          type: 'text',
          label: 'Request Title',
          placeholder: 'Enter request title',
          required: true,
          order: 0,
          validation: { max: 200 },
        },
        {
          id: 'sub_department',
          type: 'select',
          label: 'Request Type',
          required: true,
          order: 1,
          options: [
            { label: 'Get IT help', value: 'Get IT help' },
            { label: 'Access mail Inbox', value: 'Access mail Inbox' },
            { label: 'Remote Access - VPN', value: 'Remote Access - VPN' },
            { label: 'Computer Support', value: 'Computer Support' },
            { label: 'License Support', value: 'License Support' },
            { label: 'Request New software', value: 'Request New software' },
            { label: 'Request New hardware', value: 'Request New hardware' },
            { label: 'Mobile Device Issues', value: 'Mobile Device Issues' },
            { label: 'Permission access', value: 'Permission access' },
            { label: 'Reset Password', value: 'Reset Password' },
            { label: 'Printing/printer Issue', value: 'Printing/printer Issue' },
            { label: 'Work from home equipment', value: 'Work from home equipment' },
            { label: 'General Support', value: 'General Support' },
          ],
        },
        {
          id: 'priority',
          type: 'select',
          label: 'Priority',
          required: true,
          order: 2,
          options: [
            { label: 'Low', value: 'low' },
            { label: 'Medium', value: 'medium' },
            { label: 'High', value: 'high' },
            { label: 'Urgent', value: 'urgent' },
          ],
          defaultValue: 'medium',
        },
        {
          id: 'location_id',
          type: 'location',
          label: 'Location',
          required: false,
          order: 3,
        },
        {
          id: 'description',
          type: 'textarea',
          label: 'Description',
          placeholder: 'Provide detailed information about your request',
          required: true,
          order: 4,
        },
      ],
      is_active: true,
      settings: {},
    },

    // Technology Training Request
    {
      company_id: companyId,
      name: 'Technology Training Request',
      description: 'Request system and application training',
      form_type: 'department',
      department: 'technology_training',
      fields: [
        {
          id: 'title',
          type: 'text',
          label: 'Request Title',
          placeholder: 'Enter request title',
          required: true,
          order: 0,
          validation: { max: 200 },
        },
        {
          id: 'sub_department',
          type: 'select',
          label: 'Training Type',
          required: true,
          order: 1,
          options: [
            { label: 'Request Kestral training', value: 'Request Kestral training' },
            { label: 'Request PACS training', value: 'Request PACS training' },
            { label: 'Request Eftpos training', value: 'Request Eftpos training' },
            { label: 'Request CT Canon Apps training', value: 'Request CT Canon Apps training' },
            { label: 'Request CT Siemens Apps training', value: 'Request CT Siemens Apps training' },
            { label: 'Request MRI Siemens Apps training', value: 'Request MRI Siemens Apps training' },
            { label: 'Request X-ray Apps Training', value: 'Request X-ray Apps Training' },
            { label: 'Request US Canon Apps training', value: 'Request US Canon Apps training' },
            { label: 'Request US Philips Apps training', value: 'Request US Philips Apps training' },
            { label: 'Request US GE Apps training', value: 'Request US GE Apps training' },
            { label: 'Request Lumicare training', value: 'Request Lumicare training' },
          ],
        },
        {
          id: 'priority',
          type: 'select',
          label: 'Priority',
          required: true,
          order: 2,
          options: [
            { label: 'Low', value: 'low' },
            { label: 'Medium', value: 'medium' },
            { label: 'High', value: 'high' },
            { label: 'Urgent', value: 'urgent' },
          ],
          defaultValue: 'medium',
        },
        {
          id: 'location_id',
          type: 'location',
          label: 'Location',
          required: false,
          order: 3,
        },
        {
          id: 'description',
          type: 'textarea',
          label: 'Description',
          placeholder: 'Provide detailed information about your training request',
          required: true,
          order: 4,
        },
      ],
      is_active: true,
      settings: {},
    },
  ];

  const results = [];
  for (const template of templates) {
    try {
      const { data, error } = await supabase
        .from('form_templates')
        .upsert(
          {
            ...template,
            fields: template.fields as any,
          },
          {
            onConflict: 'company_id,form_type,department,sub_department',
            ignoreDuplicates: false,
          }
        )
        .select()
        .single();

      if (error) {
        console.error(`Error seeding ${template.name}:`, error);
        results.push({ name: template.name, success: false, error });
      } else {
        console.log(`Successfully seeded: ${template.name}`);
        results.push({ name: template.name, success: true, data });
      }
    } catch (err) {
      console.error(`Exception seeding ${template.name}:`, err);
      results.push({ name: template.name, success: false, error: err });
    }
  }

  return results;
}
