-- Seed Department Templates
INSERT INTO public.department_templates (department, fields, version, is_active) VALUES
('Admin Managers', '[{"key":"team_updates","label":"Team updates","type":"textarea","required":true},{"key":"training_development","label":"Training & development","type":"textarea","required":true},{"key":"operations_achievements","label":"Operations & achievements","type":"textarea","required":true},{"key":"projects_systems_upgrades","label":"Projects/systems/upgrades","type":"textarea","required":true},{"key":"recognition_culture","label":"Recognition & culture","type":"textarea","required":true},{"key":"additional_announcements","label":"Additional announcements","type":"textarea","required":false}]'::jsonb, 1, true),
('CMO', '[{"key":"clinical_governance_quality","label":"Clinical governance & quality","type":"textarea","required":true},{"key":"radiologist_performance","label":"Radiologist performance","type":"textarea","required":true},{"key":"patient_safety_incidents","label":"Patient safety/incidents","type":"textarea","required":true},{"key":"clinical_training","label":"Clinical training","type":"textarea","required":true},{"key":"accreditation_compliance","label":"Accreditation & compliance","type":"textarea","required":true},{"key":"medical_resource_planning","label":"Medical resource planning","type":"textarea","required":true},{"key":"additional","label":"Additional","type":"textarea","required":false}]'::jsonb, 1, true),
('Commercial/Marketing', '[{"key":"campaigns_promotions","label":"Campaigns & promotions","type":"textarea","required":true},{"key":"events_sponsorships","label":"Events & sponsorships","type":"textarea","required":true},{"key":"brand_communications","label":"Brand & communications","type":"textarea","required":true},{"key":"partnerships_community","label":"Partnerships & community","type":"textarea","required":true},{"key":"recognition_team_updates","label":"Recognition & team updates","type":"textarea","required":true},{"key":"additional","label":"Additional","type":"textarea","required":false}]'::jsonb, 1, true),
('Finance', '[{"key":"financial_performance","label":"Financial performance","type":"textarea","required":true},{"key":"strategic_initiatives_projects","label":"Strategic initiatives/projects","type":"textarea","required":true},{"key":"operational_process_updates","label":"Operational/process updates","type":"textarea","required":true},{"key":"people_development","label":"People & development","type":"textarea","required":true},{"key":"recognition","label":"Recognition","type":"textarea","required":true},{"key":"additional","label":"Additional","type":"textarea","required":false}]'::jsonb, 1, true),
('IT', '[{"key":"system_performance","label":"System performance","type":"textarea","required":true},{"key":"upgrades_new_implementations","label":"Upgrades/new implementations","type":"textarea","required":true},{"key":"security_compliance","label":"Security & compliance","type":"textarea","required":true},{"key":"support_service","label":"Support & service","type":"textarea","required":true},{"key":"avg_ticket_resolution_time","label":"Avg ticket resolution time","type":"text","required":false},{"key":"upcoming_projects","label":"Upcoming projects","type":"textarea","required":true},{"key":"additional","label":"Additional","type":"textarea","required":false}]'::jsonb, 1, true),
('HR / People & Culture / OHS', '[{"key":"engagement_culture","label":"Engagement & culture","type":"textarea","required":true},{"key":"learning_development","label":"Learning & development","type":"textarea","required":true},{"key":"wellbeing_support","label":"Wellbeing & support","type":"textarea","required":true},{"key":"policy_compliance_ohs","label":"Policy/compliance/OHS (incidents, corrective actions)","type":"textarea","required":true},{"key":"additional","label":"Additional","type":"textarea","required":false}]'::jsonb, 1, true),
('Operations Managers', '[{"key":"strategic_operational_updates","label":"Strategic & operational updates","type":"textarea","required":true},{"key":"people_culture","label":"People & culture","type":"textarea","required":true},{"key":"projects_expansions_investments","label":"Projects/expansions/investments","type":"textarea","required":true},{"key":"risk_compliance_safety","label":"Risk/compliance/safety","type":"textarea","required":true},{"key":"recognition_wins","label":"Recognition & wins","type":"textarea","required":true},{"key":"retention_percentage","label":"Call retention %","type":"text","required":false},{"key":"abandonment_rate","label":"Call abandonment %","type":"text","required":false},{"key":"additional","label":"Additional","type":"textarea","required":false}]'::jsonb, 1, true),
('Technical Partners', '[{"key":"team_updates","label":"Team updates","type":"textarea","required":true},{"key":"training","label":"Training","type":"textarea","required":true},{"key":"clinic_events_highlights","label":"Clinic events & highlights","type":"textarea","required":true},{"key":"operational_project_updates","label":"Operational/project updates (equipment, upgrades, community)","type":"textarea","required":true},{"key":"recognition","label":"Recognition","type":"textarea","required":true},{"key":"additional_comments","label":"Additional comments","type":"textarea","required":false}]'::jsonb, 1, true),
('Workflow Manager', '[{"key":"radiologist_availability","label":"Radiologist availability","type":"textarea","required":true},{"key":"reporting_turnaround_capacity","label":"Reporting turnaround/capacity","type":"textarea","required":true},{"key":"workflow_improvements","label":"Workflow improvements","type":"textarea","required":true},{"key":"system_process_issues","label":"System/process issues","type":"textarea","required":true},{"key":"interdepartmental_awareness","label":"Interdepartmental awareness","type":"textarea","required":true},{"key":"recognition_wins","label":"Recognition & wins","type":"textarea","required":true},{"key":"additional","label":"Additional","type":"textarea","required":false}]'::jsonb, 1, true);

-- Seed Department Assignments
INSERT INTO public.department_assignments (department, assignee_ids, allow_multiple_clinics) VALUES
('Finance', '{}', false),
('Commercial/Marketing', '{}', false),
('Admin Managers', '{}', false),
('Operations Managers', '{}', false),
('Workflow Manager', '{}', false),
('IT', '{}', false),
('HR / People & Culture / OHS', '{}', false),
('CMO', '{}', false),
('Technical Partners', '{}', true)
ON CONFLICT (department) DO NOTHING;